# yaml-language-server: =https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: hidaba.HidaChat
PackageVersion: 1.0.0
MinimumOSVersion: 10.0.19041.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: HidaChat.exe
    PortableCommandAlias: hidachat
Commands:
  - hidachat
ReleaseDate: 2026-09-19
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/hidaba/HidaChat/releases/download/v1.0.0/HidaChat-v1.0.0.zip
    InstallerSha256: F49621EB853CB36D9A30E0F331CBAA0E6D01CBE948FF29D33E84BF867DBFCFF2
ManifestType: installer
ManifestVersion: 1.6.0
