# yaml-language-server: =https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: hidaba.HidaChat
PackageVersion: 1.0.0
MinimumOSVersion: 10.0.19041.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: HidaChat.exe
    PortableCommandAlias: hidachat
Commands:
  - hidachat
ReleaseDate: 2026-09-19
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/hidaba/HidaChat/releases/download/v1.0.0/HidaChat-v1.0.0.zip
    InstallerSha256: 14FDD7C5CDCAC4E4C8259E74E47A85FE4F2CCD489FD28A70EE8E025182266EFE
ManifestType: installer
ManifestVersion: 1.6.0
